
#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require



#include "raycommon.glsl"
#include "host_device.h"
#include "random.glsl"

// clang-format off
layout(location = 0) rayPayloadEXT rayPayload payload;

layout(set = 0, binding = eTlas) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = eOutImage, rgba32f) uniform image2D image;
layout(set = 1, binding = eGlobals) uniform _GlobalUniforms { GlobalUniforms uni; };
layout(push_constant) uniform _PushConstantRay { PushConstantRay pcRay; };
// clang-format on

const int NBSAMPLES = 1;
const uint MAX_DEPTH = 10;

void main()
{
    // Initialize the random number
    payload.random_seed = InitRandomSeed(gl_LaunchIDEXT.y * gl_LaunchSizeEXT.x + gl_LaunchIDEXT.x, pcRay.frame);

    vec3 output_color = vec3(0);
    uint depth = 0;

    const uint  rayFlags = gl_RayFlagsOpaqueEXT;
    const float tMin     = 0.001;
    const float tMax     = 10000.0;

    for(int smpl = 0; smpl < NBSAMPLES; smpl++){
        // gaussian AA
        vec2 rndvec = randomGaussian(payload.random_seed);
        float r1 = rndvec.x;
        float r2 = rndvec.y;

        // square AA
        //float r1 = rnd(seed);
        //float r2 = rnd(seed);

        // Subpixel jitter: send the ray through a different position inside the pixel
        // each time, to provide antialiasing.
        vec2 subpixel_jitter = pcRay.frame == 0 ? vec2(0.5f, 0.5f) : vec2(r1, r2);
        const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5) + 0.375 *subpixel_jitter;
        const vec2 inUV        = pixelCenter / vec2(gl_LaunchSizeEXT.xy);
        vec2       d           = inUV * 2.0 - 1.0;

        //defocus blur
        float Aperture = pcRay.camAperture;
        float focus_dist = pcRay.focusDist;
        vec2 offset = (Aperture/2) * RandomInUnitDisk(payload.random_seed);
        vec3 origin    = (uni.viewInverse * vec4(offset, 0, 1)).xyz;
        vec3 target    = (uni.projInverse * vec4(d.x, d.y, 1, 1)).xyz;
        vec3 direction = (uni.viewInverse * vec4(normalize(target.xyz*focus_dist - vec3(offset, 0)), 0)).xyz;


        resetPayload(payload, origin, direction);

        // Path Tracing
        vec3 normal = normalize(target); // TO-DO: reemplazar con normal desde la camara
        vec3 contribution = vec3(1); //precargar con la funcion W_e de Veach (si es necesario)
        for(depth = 0; depth < MAX_DEPTH && payload.status == CONTINUE; depth++) {
            traceRayEXT(topLevelAS, rayFlags, 0xFF, 0, 0, 0, payload.origin, tMin, payload.direction, tMax, 0);

            // Calcular G
            // asumiendo normales y direcciones normalizadas, eliminar comentario cuando nos aseguremos que lo ...
            //  sean, para que el dot sea el ángulo
            // juntar en una linea luego de verificar funcionamiento

            float cos_phi_0 = dot(normal, direction);
            float cos_phi_i = dot(payload.surface_normal, -direction);
            vec3 diff = origin - payload.origin;
            float G = abs(cos_phi_0 * cos_phi_i) / dot(diff, diff);

            // Para el caso de la luz, el L_e viene en el payload.bsdf_sample, por lo que no altera la fórmula.
            contribution *= payload.bsdf_sample;

            origin    = payload.origin;
            direction = payload.direction;
            normal = payload.surface_normal;
        }

        // Rays that don't make it to a light don't contribute to the result
        output_color += contribution * int(depth < MAX_DEPTH);
    }

    output_color = output_color / NBSAMPLES;

    if(pcRay.frame > 0)
    {   //Accumulation over time
        float a         = 1.0f / float(pcRay.frame + 1);
        vec3  old_color = imageLoad(image, ivec2(gl_LaunchIDEXT.xy)).xyz;
        imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(mix(old_color, output_color, a), 1.f));
    }
    else
    {   // First frame, replace the value in the buffer
        imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(output_color, 1.f));
    }
}
